language : node_js
node_js :  
  - stable
install:  
  - npm install
script:  
  - npm run ci
# Update Coveralls
after_script: "npm run coveralls"
branches:
  only:
    - master
before_deploy:
  - touch .nojekyll
  - sed -i '/doc/d' .gitignore